### ISSUE TITLE
Includes pre-compiled Tesseract (3.04.01) for your platform???

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract4java/tesseract4java#13]
Announcement email says:

> Includes pre-compiled Tesseract (3.04.01) for your platform, just click and run it! Traineddata is not included, though.

However, when running the program, edit preferences needs location of tesseract executable.

Also, there is no way to make that path selection blank for the location of tesseract executable to use the bundled binary.

(32bit version running on windows 10)

**Comment by pvorb** [comment]
@Shreeshrii First, thanks for all the feedback. It is much appreciated! I'll do my best to transform your advice into a 0.2 release soon.

To your question:

In a pre-release version there was a need for having the Tesseract executables installed locally. That's why I added a setting to the preferences dialog. However, the current release comes with Tesseract binaries included, so you no longer need to define the setting.

There's one exception: If you want to use the Tesseract Trainer (Tools &rarr; Tesseract Trainer...), you still need to specify your Tesseract installation folder, but that is also possible via the trainer dialog itself.

So I suggest simply removing that setting.

**Comment by Shreeshrii** [comment]
> you no longer need to define the setting.

Yes. But, having entered the path, there is no way for me to remove it. It only allows for selection of a new directory.

Hence, I am not sure whether it is using the bundled binary or the one pointed by the path setting here.

**Comment by pvorb** [comment]
@Shreeshrii I removed the setting from future versions. If you want to remove the setting in the current release, you can manually remove the following key from the Windows Registry (regedit.exe): `HKEY_CURRENT_USER\Software\JavaSoft\Prefs\de\vorb\tesseract\gui\model\exec_dir`

(Obviously, this won't work with Linux and Mac OS X)
